# Generated by Django 2.1.2 on 2018-10-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='json',
            new_name='value',
        ),
        migrations.AddField(
            model_name='value',
            name='group',
            field=models.ForeignKey(limit_choices_to=models.Q(group__value='group'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_related', to='toko.Value'),
        ),
    ]
