# Generated by Django 2.1.2 on 2018-10-23 00:42

from django.db import migrations, models
import toko.utils.file


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(unique=True, upload_to=toko.utils.file.get_upload_path),
        ),
    ]
