# Generated by Django 2.1.2 on 2018-10-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_auto_20181029_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(group__value='group'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_related', to='toko.Value'),
        ),
    ]
