# Generated by Django 2.1.1 on 2018-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_auto_20180927_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
