# Generated by Django 2.1.2 on 2018-10-29 12:30

from django.db import migrations, models
import django.db.models.deletion
import toko.models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_auto_20181029_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='group',
            field=models.ForeignKey(default=3, limit_choices_to=toko.models.group_value_filter, on_delete=django.db.models.deletion.CASCADE, related_name='field_group_related', to='toko.Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to=toko.models.group_value_filter, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_related', to='toko.Value'),
        ),
    ]
