# Generated by Django 2.1.1 on 2018-10-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_auto_20180930_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name_plural': 'Taxonomies'},
        ),
    ]
