# Generated by Django 2.1.1 on 2018-09-27 15:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_auto_20180927_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={},
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='order',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='toko.Taxonomy'),
        ),
    ]
