# Generated by Django 2.1.1 on 2018-10-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0005_auto_20181002_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabupaten',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kabupaten',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='provinsi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provinsi',
            name='updated_at',
        ),
    ]
