# Generated by Django 2.1.1 on 2018-10-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0006_auto_20181002_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=4000)),
                ('Kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.Kabupaten')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.Taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='images',
            field=models.ManyToManyField(to='toko.File'),
        ),
        migrations.AddField(
            model_name='ad',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.Provinsi'),
        ),
    ]
