# Generated by Django 2.1.1 on 2018-10-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0007_auto_20181003_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='Kabupaten',
            new_name='kabupaten',
        ),
    ]
