# Generated by Django 2.1.1 on 2018-10-05 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toko.utils.file


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_auto_20181004_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='toko.Ad'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to=toko.utils.file.get_ad_img_upload_path),
        ),
    ]
