# Generated by Django 2.1.1 on 2018-10-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0013_auto_20181006_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
