# Generated by Django 2.1.1 on 2018-10-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0014_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='nego',
            field=models.BooleanField(default=True, verbose_name='Bisa nego'),
            preserve_default=False,
        ),
    ]
