# Generated by Django 2.1.1 on 2018-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0015_ad_nego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='nego',
            field=models.BooleanField(),
        ),
    ]
